name: Like a Story
description: Mark a story as interesting/valuable
title: "[Like] "
labels: ["feedback:like"]
body:
  - type: input
    id: cluster_id
    attributes:
      label: Cluster ID
      description: The cluster_id from the story (found in latest.json)
      placeholder: e.g. abc123def456
    validations:
      required: true
  - type: input
    id: topic
    attributes:
      label: Topic
      description: Brief description of what you liked
      placeholder: e.g. AI research coverage
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any additional feedback
    validations:
      required: false
